config/routes.rb
Rails.application.routes.draw do

  get 'registrations/new'
  root to: 'static_pages#home'
  resources :static_pages

  resources :users do 
  	resources :gossips do 
  		resources :commentaries
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/commentary.rb
class Commentary < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user

	has_many :commentaries
	has_many :likes

	has_and_belongs_to_many :tags
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	belongs_to :commentary
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	has_and_belongs_to_many :recipients, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city, optional: true
	has_many :gossips
	has_many :commentaries
	has_many :likes

  	has_many :sent_messages, class_name: "PrivateMessage", foreign_key: "sender_id"
	has_and_belongs_to_many :received_messages, class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commentaries_controller.rb
class CommentariesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @gossip = Gossip.find(params[:gossip_id])
    @commentaries = Commentary.all
  end

  def new
    @user = User.find(params[:user_id])
    p "''''''''''''''''''''''''''"
    puts @user.id
    @gossip = Gossip.find(params[:gossip_id])
    p "''''''''''''''''''''''''''"
    puts @gossip.id
    @commentary = Commentary.new
    puts @commentary
  end

  def create
    p @user = User.find(params[:user_id])
    p @gossip = Gossip.find(params[:gossip_id])
    puts "'''''''''''''''''''''''REGARDE ICI''''''''''''''''''''''''''"
    p commentary = Commentary.create(content: params[:commentary][:content], user_id: params[:user_id], gossip_id: params[:gossip_id])
    redirect_to(user_gossip_path(@user.id, @gossip.id))
  end

  def show
    @user = User.find(params[:user_id])
    @gossip = Gossip.find(params[:gossip_id])
    # @commentary = Commentary.new
  end

  def edit
    @user = User.find(params[:user_id])
    @gossip = Gossip.find(params[:id])
    @commentary = Commentary.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @gossip = Gossip.find(params[:id])
    @commentary = Commentary.find(params[:id])
    @commentary.update(content: params[:commentary][:content], user_id: params[:commentary][:user_id], gossip_id: params[:commentary][:gossip_id])
    redirect_to user_gossip_path
  end

  def destroy
    @user = User.find(params[:user_id])
    @gossip = Gossip.find(params[:id])
    @commentary = Commentary.find(params[:id])
    @commentary.destroy
    redirect_to commentaries_path
  end

  # private

  # def commentary_params
  #   result = params.require(:commentary).permit(:content)
  #   result[:user_id] = params[:user_id]
  #   result[:gossip_id] = params[:gossip_id]
  #   return result
  # end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @user = User.find(params[:user_id]) 
    @gossips = Gossip.all

  end

  def create
    gossip = Gossip.create(gossip_params)
    p "*****************"
    p gossip_params
    p "*****************"
    p gossip
    redirect_to user_gossips_path(gossip.user_id)
  end

  def show
    @user = User.find(params[:user_id])
    @gossip = Gossip.find(params[:id])
    @gossip_commentaries = Gossip.find(params[:id]).commentaries
    puts "'''''''''''''''''''''''''''''''''''''''''''"
    puts @gossip_commentaries
  end

  def new
    @gossip = Gossip.new
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    redirect_to user_gossips_path
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to user_gossips_path
  end

  private

  def gossip_params
    result = params.require(:gossip).permit(:title, :content)
    result[:user_id] = params[:user_id]
    return result
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    p "Regarde ici"
    p @user
    redirect_to user_gossips_path(@user.id)
  end

  def new
    @user = User.new
    p "Je suis new"
    p @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def gossip_params
    params.require(:gossip).permit(:title, :content, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commentary_helper.rb
module CommentaryHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commentaries/create.html.erb
<h1>Commentary#create</h1>
<p>Find me in app/views/commentary/create.html.erb</p>

app/views/commentaries/destroy.html.erb
<h1>Commentary#destroy</h1>
<p>Find me in app/views/commentary/destroy.html.erb</p>

app/views/commentaries/edit.html.erb
<h1> Editer un commentaire </h1>

<%= form_for @commentary, :url => user_gossip_commentary_path do |f| %>
	</div>
	<div class="form-group">
		<label>Contenu :</label>
		  <%= f.text_area :content, class: 'form-control' %>
	</div>
  <%= f.submit "modifier", class:"btn btn-primary" %>
<% end %>

app/views/commentaries/index.html.erb
<h1>Commentaires</h1>
<p>Listes :</p>

<table class="table">
	<thead>
		<tr>
			<td>GOSSIP_ID</td>
			<td>ID</td>
			<td>Contenu</td>
			<td>Action</td>
		</tr>

	</thead>

	<tbody>
		<%  @commentaries.each do |comment| %>
		<tr>
			<td><%=  comment.gossip.id %></td>
			<td><%=  comment.id %></td>
			<td><%=  comment.content %></td>
			
		</tr>
		<tr>

		</tr>
		<%  end %>

	</tbody>
</table>

<p>
	<a href=" <%= new_user_gossip_commentary_path %> " class="btn btn-success">Commenter</a>
</p>

app/views/commentaries/new.html.erb
<h1> Créer un commentaire </h1>

<%= form_for @commentary, :url => user_gossip_commentaries_path do |f| %>
	<div class="form-group">
		<label>Contenu :</label>
		  <%= f.text_area :content, class: 'form-control' %>
	</div>
  <%= f.submit "Créer le commentaire", class:"btn btn-primary" %>
<% end %>

app/views/commentaries/show.html.erb
<h1>Commentary#show</h1>
<p>Find me in app/views/commentary/show.html.erb</p>

app/views/commentaries/update.html.erb
<h1>Commentary#update</h1>
<p>Find me in app/views/commentary/update.html.erb</p>

app/views/gossips/edit.html.erb
<h1> Editer un gossip </h1>

<%= form_for @gossip, :url => user_gossip_path do |f| %>

	<div class="form-group">
		<label>Titre du gossip :</label>
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>Contenu :</label>
		  <%= f.text_area :content, class: 'form-control' %>
	</div>
  <%= f.submit "Modifie le gossip", class:"btn btn-primary" %>
<% end %>

app/views/gossips/index.html.erb
<h1> Bonjour <%= @user.name %> </h1>
<h2>Gossips</h2>
<p>Listes :</p>

<table class="table">
	<thead>
		<tr>
			<td>USER_ID</td>
			<td>Titre</td>
			<td>Contenu</td>
		</tr>

	</thead>

	<tbody>
		<%  @gossips.each do |gossip| %>
		<tr>
			<td><%=  gossip.user.id %></td>
			<td><%= gossip.title %></td>
			<td><%= gossip.content %></td>
		</tr>
		<tr>
			<td><%= link_to "Voir", user_gossip_path(@user.id, gossip.id), class: "btn btn-lg btn-primary" %></td>
			<td><%= link_to "Editer", edit_user_gossip_path(@user.id, gossip.id), class: "btn btn-lg btn-succes" %></td>
			<td><a href=" <%= user_gossip_path(@user.id, gossip.id) %> " class="btn btn-lg btn-danger" data-confirm="Etes vous sûr ?" data-method="DELETE">Supprimer le gossip</a></td>
		</tr>
		<%  end %>
	</tbody>
</table>


<p>
	<a href=" <%= new_user_gossip_path %> " class="btn btn-success">Créer un gossip</a>
</p>

app/views/gossips/new.html.erb
<h1> Créer un gossip </h1>

<%= form_for @gossip, :url => user_gossips_path(params[:user_id]) do |f| %>
	<div class="form-group">
		<label>Titre du gossip :</label>
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>Contenu :</label>
		  <%= f.text_area :content, class: 'form-control' %>
	</div>
  <%= f.submit "Créer le post", class:"btn btn-primary" %>
<% end %>

app/views/gossips/show.html.erb
<h1>User ID : <%= @gossip.user_id %></h1>

<h1>Titre du Gossip : <%= @gossip.title %></h1>

<p><%=  @gossip.content %></p>

<table class="table">
	<thead>
		<tr>
			<td>Commentaires :</td>
		</tr>

	</thead>

	<tbody>
		<%  @gossip_commentaries.each do |gossip_comment| %>
		<tr>

			<td><%=  gossip_comment.content %></td>

		</tr>
		<tr>
			<td><%= link_to "Voir", user_gossip_commentary_path(@user.id, gossip_comment.id, gossip_comment.id), class: "btn btn-lg btn-primary" %></td>
			<td><%= link_to "Editer", edit_user_gossip_commentary_path(@user.id, gossip_comment.id, gossip_comment.id), class: "btn btn-lg btn-succes" %></td>
			<td><%= link_to "Créer", new_user_gossip_commentary_path(@user.id, gossip_comment.id), class: "btn btn-lg btn-succes" %></td>
			<td><a href=" <%= user_gossip_commentary_path(@user.id, gossip_comment.id, gossip_comment.id) %> " class="btn btn-lg btn-danger" data-confirm="Etes vous sûr ?" data-method="DELETE">Supprimer</a></td>
		</tr>
		<%  end %>
	</tbody>
</table>

<p><%= link_to "Commenter", new_user_gossip_commentary_path(@user.id, @gossip.id), class: "btn btn-succes" %></p>
<a href=" <%= user_gossips_path %> " class="btn btn-primary">Revenir aux gossips</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   '/' %></li>
        <li>
          <% if params[:user_id] %>
            <%=link_to "Index des gossips", user_gossips_path %>
          <% end %>
        </li>
        <li>
          <% if params[:user_id] %>
            <%=link_to "Nouveau gossip", new_user_gossip_path %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", new_user_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1> Créer un user </h1>

<%= form_for @user do |f| %>
  <div class="form-group">
    <label>Nom :</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Email :</label>
      <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Password :</label>
      <%= f.text_field :password, class: 'form-control' %>
  </div>
  <%= f.submit "Enregistrement", class:"btn btn-primary" %>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>